New Page About Broccoli
karlwithak/lecture-notes pull request #1
Opened 2023-05-29 20:12 UTC by karlwithak

Adds a new html and css file for the broccoli page

![image](https://github.com/karlwithak/lecture-notes/assets/3248771/617a0d62-6213-4189-aefc-27047c68e74f)

2023-05-31 10:13 UTC, karlwithak reviewed
looks great!

2023-05-31 10:13 UTC, karlwithak commented on code-reviews/example1/index.html
> +        <h2>Broccoli 🥦</h2>
I think we should remove the emoji!

2023-05-31 10:27 UTC, Griffins2005 commented
looks great

2023-05-31 10:27 UTC, collinsmathinji commented on code-reviews/example1/index.html
> +            <li>Tastes Great</li>
you sure its tasty?

2023-05-31 10:28 UTC, Mwangangi1978 commented on code-reviews/example1/styles.css
> +    color: black;
maybe white would be better

2023-05-31 10:29 UTC, collinsmathinji commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
h3 why use capital?

2023-05-31 10:29 UTC, Leevy-Otieno commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
h3 should start in lower case

2023-05-31 10:30 UTC, AlvinKab commented on code-reviews/example1/index.html
> +            <li>Tastes Great</li>
ok

2023-05-31 10:30 UTC, Obarajames commented on code-reviews/example1/index.html
> +    <div class='main'>
reduce the margin from the top

2023-05-31 10:31 UTC, collinsmathinji commented on code-reviews/example1/index.html
> +    <title>All About Broccoli</title>
why not put an icon for your webpage?

2023-05-31 10:31 UTC, AlvinKab commented on code-reviews/example1/index.html
> +            <li>Tastes Great</li>
ok

2023-05-31 10:32 UTC, Pkorirdarius commented on code-reviews/example1/styles.css
> +recipes {
The class recipe has not been referenced well:I think it should be .recipes ,The dot was not included

2023-05-31 10:33 UTC, Obarajames commented on code-reviews/example1/index.html
> +            Please email me with your favourite recipes!
Add  a link to enable people to be able send email

2023-05-31 10:34 UTC, Griffins2005 commented on code-reviews/example1/index.html
> +        <p>A humble and delicious vegetable</p>
looks great.

2023-05-31 10:34 UTC, Brikita commented on code-reviews/example1/styles.css
> +    background-color: #add8e6;
I dont like the color

2023-05-31 10:35 UTC, G3orge0tevin reviewed
👍

2023-05-31 10:35 UTC, G3orge0tevin commented on code-reviews/example1/styles.css
👍

2023-05-31 10:36 UTC, jjibrah requested changes
Your should check on your h3 tag

2023-05-31 10:36 UTC, jjibrah commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
are you sure you have used the correct h3 tag

2023-05-31 10:36 UTC, t-ed-c commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
sure thing

2023-05-31 10:37 UTC, Mwangangi1978 commented on code-reviews/example1/styles.css
> +    color: black;
mabe white would be better?

2023-05-31 10:37 UTC, SimonSallstrom commented on code-reviews/example1/index.html
> +        <h2>Broccoli 🥦</h2>
Good choice! I Like Broccoli :)

2023-05-31 10:37 UTC, SimonSallstrom commented on code-reviews/example1/index.html
> +            <li>Tastes Great</li>
What do you think about doing 3 things instead? As they say, all good things come in 3 :)

2023-05-31 10:37 UTC, AlvinKab commented on code-reviews/example1/index.html
> +            <li>Tastes Great</li>
ok

2023-05-31 10:37 UTC, patrickleon710 reviewed
Could you change the color?

2023-05-31 10:37 UTC, Willylaisa reviewed
Great work though!!!

2023-05-31 10:37 UTC, Willylaisa commented on code-reviews/example1/index.html
> +    <meta charset="UTF-8">
I think there are some missing meta tags...
For instance, I'm not really sure about this but I think web developers add their names and the following:
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1.0">

2023-05-31 10:37 UTC, Willylaisa commented on code-reviews/example1/index.html
> +        <h2>Broccoli 🥦</h2>
Why didn't you start with a h1?

2023-05-31 10:37 UTC, Willylaisa commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
Why did you use capital in the tags? I think it's syntactically wrong... I'm not sure though...

2023-05-31 10:37 UTC, theeurbanlegend commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
Will the code still look grammatically nice if you use h3 tag in capital letters?

2023-05-31 10:37 UTC, theeurbanlegend commented on code-reviews/example1/index.html
> +    <title>All About Broccoli</title>
what happens if the user requires to view it on a smaller screen device/could u add a metatag for viewport width

2023-05-31 10:37 UTC, theeurbanlegend commented on code-reviews/example1/styles.css
> +recipes {
Will the styles really apply when the class "styles" is referenced without a dot at the start?

2023-05-31 10:37 UTC, Willylaisa reviewed
Great work though!!!

2023-05-31 10:37 UTC, Brikita reviewed
Its okay

2023-05-31 10:37 UTC, Cal-Davis reviewed
How about you use a list to display the things you can do with broccoli (under class ="recipes")

2023-05-31 10:37 UTC, RealTim0 commented on code-reviews/example1/index.html
> +        <p>Here are my favourite things about it</p>
what about including a colon at the end?

2023-05-31 10:37 UTC, RealTim0 commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
Shouldn't the H in H3 tag be lower case?

2023-05-31 10:37 UTC, RealTim0 commented on code-reviews/example1/styles.css
> +recipes {
what about putting it as .recipes as it is a a class?

2023-05-31 10:37 UTC, itsbluejelly commented on code-reviews/example1/index.html
> +    <title>All About Broccoli</title>
what if you add the meta viewport tag? I think it can help with screen responsiveness

2023-05-31 10:37 UTC, itsbluejelly commented on code-reviews/example1/index.html
> +    <div class='main'>
Why did u enclose the content in a div tag? I don't think it affects the code in any way

2023-05-31 10:38 UTC, lizziegitau commented on code-reviews/example1/index.html
> +            I love roasting it, and eating it in salads.
I didn't know you can roast broccoli

2023-05-31 10:41 UTC, Jhn-Gi commented on code-reviews/example1/index.html
> +        <H3>What you can do with broccoli</H3>
True

2023-05-31 10:42 UTC, t-ed-c commented on code-reviews/example1/index.html
> +        <h2>Broccoli 🥦</h2>
thats a tree emoji

2023-05-31 10:43 UTC, t-ed-c commented on code-reviews/example1/index.html
> +</html>
looking good

2024-06-04 11:45 UTC, karlwithak commented
Closing, so I can re-open for new cohort!

2024-06-04 11:45 UTC, closed without merging